baseURL = "https://prail.net/"
languageCode = "en-us"
title = "Prail.Net Worldwide Headquarters"
theme = "ananke"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[params]
  description = "The New Prail.Net"
  facebook = "https://www.facebook.com/ingrid.prail/"
  github = "https://github.com/PrailNet"
  featured_image = "/images/hero.jpg"
